### ISSUE TITLE
Migrate to Angular Components

### ISSUE THREAD

**Issue by bampakoa** [ibbatta/grunt-frontend-boilerplate#3]
@ibbatta What do you think about migrating from controllers to components as of Angular 1.5?

**Comment by ibbatta** [comment]
@bampakoa I was thinking in these days. I need to learn more about and start develop something

**Comment by bampakoa** [comment]
Ok, ping me if you need some help. I would be happy to contribute. I could also make a PR with one converted controller to component and you could take on from there.

**Comment by ibbatta** [comment]
@bampakoa I already told that i love you, right? ahahah
Thanks mate, I really appreciate it (I also need some guide to study, If you have some to suggests)

**Comment by bampakoa** [comment]
There is no need to study a particular guide really. All you have to do is read the appropriate section about [components](https://docs.angularjs.org/guide/component) in AngularJS official docs. This is what I did.

**Comment by ibbatta** [comment]
@bampakoa thanks!
